export const popular = [
  {
    url: "/popular1",
    img: "/assets/popular/1.png",
    name: "Popular 1",
    sale: true,
    favorite: true,
    stars: 3,
    price: 2555,
  },
  {
    url: "/popular2",
    img: "/assets/popular/2.png",
    name: "Popular 2",
    sale: false,
    favorite: true,
    stars: 5,
    price: 3678,
  },
  {
    url: "/popular3",
    img: "/assets/popular/3.png",
    name: "Popular 3",
    sale: false,
    favorite: false,
    stars: 1,
    price: 999,
  },
  {
    url: "/popular4",
    img: "/assets/popular/4.png",
    name: "Popular 4",
    sale: false,
    favorite: false,
    stars: 2,
    price: 19985,
  },
  {
    url: "/popular5",
    img: "/assets/popular/5.png",
    name: "Popular 5",
    sale: true,
    favorite: true,
    stars: 4,
    price: 10235,
  },
  {
    url: "/popular6",
    img: "/assets/popular/6.png",
    name: "Popular 6",
    sale: true,
    favorite: true,
    stars: 1,
    price: 22334,
  },
  {
    url: "/popular7",
    img: "/assets/popular/7.png",
    name: "Popular 7",
    sale: true,
    favorite: false,
    stars: 4,
    price: 1131,
  },
  {
    url: "/popular8",
    img: "/assets/popular/8.png",
    name: "Popular 8",
    sale: false,
    favorite: true,
    stars: 3,
    price: 1223,
  },
  {
    url: "/popular9",
    img: "/assets/popular/9.png",
    name: "Popular 9",
    sale: true,
    favorite: false,
    stars: 3,
    price: 9852,
  },
];
